### ISSUE TITLE
Script with freebox4k and zabbix 

### ISSUE THREAD

**Issue by heiwanasenshi** [FanaticalHelp/freebox-monitoring#1]
Hello, 

j'ai testé ce script avec une freebox 4k et zabbix 5.
Cela ne semble pas fonctionner.
J'ai notamment dans les log du server zabbix 
 811:20200530:182722.558 item "Freebox Server:freebox.py[connection]" became not supported: /usr/lib/zabbix/externalscripts/freebox.py: [2] No such file or directory
   811:20200530:182722.575 item "Freebox Server:freebox.py[system]" became not supported: /usr/lib/zabbix/externalscripts/freebox.py: [2] No such file or directory

J'ai bien appliqué le template et créé un host avec ce template.

Bon je suis un débutant zabbix et je voulais juste tester car je trouvais cela sympa.

Si jamais vous avez le temps de jeter un oeil.

A+

H.

**Comment by wiflye81** [comment]
Hello,

Après avoir cloné le dépôt, il faut copier le fichier fbx_monitor.py dans /usr/lib/zabbix/externalscripts/ puis le renommer en freebox.py.
Et enfin un sudo -u zabbix /usr/lib/zabbix/externalscripts/freebox.py authorize pour récupérer le token.
Il est possible que tous les items ne soient pas disponible suivant la version de la freebox.

@+

**Comment by JuDa-FR** [comment]
Bonjour,

J'ai une Freebox Delta et j'ai une erreur sur la partie "switch" du script :

```bash
 /usr/lib/zabbix/externalscripts/freebox.py switch
Status code not handled.
Traceback (most recent call last):
  File "/usr/lib/zabbix/externalscripts/freebox.py", line 342, in <module>
    print(json.dumps(getattr(monitoring, args.action)()))
  File "/usr/lib/zabbix/externalscripts/freebox.py", line 254, in switch
    return self.api.get("switch/status")
  File "/usr/lib/zabbix/externalscripts/freebox.py", line 178, in get
    return self._call_api(requests.get, url)
  File "/usr/lib/zabbix/externalscripts/freebox.py", line 168, in _call_api
    return self._send_request(method, url, json)
  File "/usr/lib/zabbix/externalscripts/freebox.py", line 164, in _send_request
    return self.parse(method(self.api_url + url, headers=headers))
  File "/usr/lib/zabbix/externalscripts/freebox.py", line 143, in parse
    raise
RuntimeError: No active exception to reraise
```
Peut-être dû au fait que j'utilise le port SFP+ de la box.

Dommage j'aimerai bien avoir la vitesse des ports du switch.

De plus, dans le template, j'ai eu a corriger l'item température du disque dur.
Ce dernier est nommé différemment sur ce modèle : "temp_hdd1"
