### ISSUE TITLE
Freeebox 4.8 - Error authentication

### ISSUE THREAD

**Issue by gamersalpha** [FanaticalHelp/freebox-monitoring#6]
Hello i can't connect with my freebox : 

```
user@zabbix:~/freebox-monitoring$ python3 ./fbx_monitor.py authorize
You need to press YES on the box.
Not authenticated.
Traceback (most recent call last):
  File "/home/stagiaire/freebox-monitoring/./fbx_monitor.py", line 337, in <module>
    monitoring.authorize()
  File "/home/stagiaire/freebox-monitoring/./fbx_monitor.py", line 232, in authorize
    self.api.authenticate()
  File "/home/stagiaire/freebox-monitoring/./fbx_monitor.py", line 104, in authenticate
    track_id = self.request_authorize()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stagiaire/freebox-monitoring/./fbx_monitor.py", line 74, in request_authorize
    app_register = self.post("login/authorize", payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stagiaire/freebox-monitoring/./fbx_monitor.py", line 185, in post
    return self._call_api(requests.post, url, json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stagiaire/freebox-monitoring/./fbx_monitor.py", line 168, in _call_api
    return self._send_request(method, url, json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stagiaire/freebox-monitoring/./fbx_monitor.py", line 162, in _send_request
    return self.parse(method(self.api_url + url, json=json, headers=headers))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stagiaire/freebox-monitoring/./fbx_monitor.py", line 139, in parse
    raise ApiError(body)
ApiError

```

how fix this please

**Comment by bontiv** [comment]
Hi,

I didn't work on this project since a very long time. Our company stopped to use Free, I can't update and test this project anymore. Now we subscribe to more expensive but more flexible telecom company.

Free have a very good hardware and software for their Freebox. But their network is not stable. It's like wheel with a Tesla on little ground road.

For your troubleshooting, you may verify this DNS: mafreebox.freebox.fr.
